import {
  responsiveFontSize,
  responsiveScreenHeight,
  responsiveScreenWidth,
} from 'react-native-responsive-dimensions';

export const DEFAULT_STYLES = Object.freeze({
  size: {
    '4': 4,
    '8': 8,
    '12': 12,
    '16': 16,
    '20': 20,
    '24': 24,
    '28': 28,
    '32': 32,
    '36': 36,
    '40': 40,
  },
  color: {
    main: '#8e7cc3',
    black: 'black',
    white: 'white',
    red: 'red',
    background: '#F5F5F5',
    transparent: 'transparent',
    chattingBackground: '#82BFE0',
    gray: '#8C8F94',
    lime: 'lime',
  },
  fontSize: {
    normal: responsiveFontSize(1.2),
    medium: responsiveFontSize(1.6),
    large: responsiveFontSize(2.0),
    extraLarge: responsiveFontSize(2.4),
    extraExtraLarge: responsiveFontSize(2.8),
    extraExtraExtraLarge: responsiveFontSize(3.2),
    extraExtraExtraExtraLarge: responsiveFontSize(3.6),
  },
  width: {
    4: responsiveScreenWidth(4),
    8: responsiveScreenWidth(8),
    12: responsiveScreenWidth(12),
    16: responsiveScreenWidth(16),
    20: responsiveScreenWidth(20),
    24: responsiveScreenWidth(24),
    28: responsiveScreenWidth(28),
    32: responsiveScreenWidth(32),
    36: responsiveScreenWidth(36),
    40: responsiveScreenWidth(40),
    44: responsiveScreenWidth(44),
    48: responsiveScreenWidth(48),
    52: responsiveScreenWidth(52),
    56: responsiveScreenWidth(56),
    60: responsiveScreenWidth(60),
    64: responsiveScreenWidth(64),
    68: responsiveScreenWidth(68),
    72: responsiveScreenWidth(72),
    76: responsiveScreenWidth(76),
    80: responsiveScreenWidth(80),
    84: responsiveScreenWidth(84),
  },
  height: {
    4: responsiveScreenHeight(4),
    8: responsiveScreenHeight(8),
    12: responsiveScreenHeight(12),
    16: responsiveScreenHeight(16),
    20: responsiveScreenHeight(20),
    24: responsiveScreenHeight(24),
    28: responsiveScreenHeight(28),
    32: responsiveScreenHeight(32),
    36: responsiveScreenHeight(36),
    40: responsiveScreenHeight(40),
    44: responsiveScreenHeight(44),
    48: responsiveScreenHeight(48),
    52: responsiveScreenHeight(52),
    56: responsiveScreenHeight(56),
    60: responsiveScreenHeight(60),
    64: responsiveScreenHeight(64),
    68: responsiveScreenHeight(68),
    72: responsiveScreenHeight(72),
    76: responsiveScreenHeight(76),
    80: responsiveScreenHeight(80),
    84: responsiveScreenHeight(84),
  },
});
